AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket for SAM deployment artifacts

Resources:
  DeploymentArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: guests-management-deployment-artifacts
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref DeploymentArtifactsBucket
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt DeploymentArtifactsBucket.Arn
